name: Deploy udacity project4

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image reverse proxy
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/reverseproxy:latest -f ./udagram-reverseproxy/Dockerfile .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/reverseproxy:latest

      - name: Build Docker image udagram-api-feed
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/udagram-api-feed:latest -f ./udagram-api-feed/Dockerfile .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/udagram-api-feed:latest

      - name: Build Docker image udagram-api-user
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/udagram-api-user:latest -f ./udagram-api-user/Dockerfile .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/udagram-api-user:latest

      - name: Build Docker image udagram-frontend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/udagram-frontend:latest -f ./udagram-udagram-frontend/Dockerfile .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/udagram-frontend:latest

          
