name: Deploy udacity project4

on:
  push:
    branches:
      - main
    tags:
      - test.v.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      #install compose 
      - name: Install Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          legacy: true 
      #check installed   
      - run: docker-compose --version

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker images
        run: docker-compose -f docker-compose-build.yaml build  --parallel

      - name: Push Docker image to Docker Hub - reverseproxy 
        run: docker push ${{ secrets.DOCKER_USERNAME }}/reverseproxy:latest

      - name: Push Docker image to Docker Hub - api-feed
        run: docker push ${{ secrets.DOCKER_USERNAME }}/udagram-api-feed:latest

      - name: Push Docker image to Docker Hub - api-user
        run: docker push ${{ secrets.DOCKER_USERNAME }}/udagram-api-user:latest

      - name: Push Docker image to Docker Hub - frontend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/udagram-frontend:latest

          
