name: Deploy udacity project4

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-west-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: MY_ECR_REPOSITORY           # set this to your Amazon ECR repository name
  ECS_SERVICE: MY_ECS_SERVICE                 # set this to your Amazon ECS service name
  ECS_CLUSTER: MY_ECS_CLUSTER                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: MY_ECS_TASK_DEFINITION # set this to the path to your Amazon ECS task definition
                                               # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: MY_CONTAINER_NAME           # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

permissions:
  contents: read

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      permissions:
        packages: write
        contents: read
        attestations: write
        id-token: write
      steps:
        - name: Check out the repo
          uses: actions/checkout@v4

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build Docker image reverse proxy
          run: docker build -t ${{ secrets.DOCKER_USERNAME }}/reverseproxy:latest .

        - name: Push Docker image to Docker Hub
          run: docker push ${{ secrets.DOCKER_USERNAME }}/reverseproxy:latest

          